# escape=`
# note SDK does not include workload "Data storage and processing"
# so cannot build database project
FROM mcr.microsoft.com/dotnet/framework/sdk:4.8 AS build

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
